name: CI

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        emacs_version: ['28.2', 'snapshot']

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: |
        curl -fsSL \
          https://raw.github.com/doublep/eldev/master/webinstall/github-eldev \
          | sh

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test the project
      run: |
        eldev -vT test
        eldev -vT compile --warnings-as-errors

    - name: Lint the project
      run: |
        eldev -p -vT lint
